# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CCNetworkTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCNetworkTool
  pod 'HandyJSON', '~> 5.0.0-beta'
  pod 'SwiftyJSON'
  pod 'Moya' , '~> 14.0.0'
  pod 'SnapKit', '~> 4.0.0' # autolayout
  pod 'MBProgressHUD', '~> 1.1.0' # 状态图

  target 'CCNetworkToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CCNetworkToolUITests' do
    # Pods for testing
  end

end
